[package]
name = "rfetch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.20.0"
ansi_term = "0.12.1"
termion = "1.5.6"
